### ISSUE TITLE
Package pulp-cli-deb

### ISSUE THREAD

**Issue by maartenbeeckmans** [theforeman/pulpcore-packaging#322]
Hi

Is it possible to package https://pypi.org/project/pulp-cli-deb/.

Wanted to create a pull request but can't find on how to create them for a pull request.

Is it possible to package this?

**Comment by Odilhao** [comment]
Hi @maartenbeeckmans,

We have the steps documented in the Readme on [foreman-packaging](https://github.com/theforeman/foreman-packaging/blob/rpm/develop/README.md#howto-add-a-package), 

You will need to fork this repository(pulcore-packaging) and use the script https://github.com/theforeman/foreman-packaging/blob/461c8df52c17de853a8a0c0657a7d18135a73229/add_pypi_package.sh to add the packages. 

---

I can take a look on the packaging of this next week, if that sounds ok to you

**Comment by evgeni** [comment]
Not against packaging it, but wonder why it's not shipped as part of the normal pulp-cli, like all the other plugins?

**Comment by maartenbeeckmans** [comment]
Will try to package it today, but @evgeni, I've read on matrix that's it seems like it's more in a poc state:

```
I am afraid pulp-deb-cli is in a proof of concept (PoC) state that does not actually provide much functionality right now. (It is more of a PoC for the pulp-cli plugin architecture than a PoC for a pulp_deb CLI).
```

But will try packaging it anyways and see if it's useful, we can always remove it when it doesn't add anything.

source: https://matrix.to/#/!ODCChMtvlSyWrYfgUR:matrix.org/$hl6SVhQGD8ugE73l6LI4d_vkxGmIMPXgsDh9Up6uU8k?via=libera.chat&via=matrix.org&via=matrix.beeckmans.cloud

**Comment by quba42** [comment]
@evgeni `pulp-cli-deb` is in a separate repo since it will ultimately need to be maintained by the same people that are maintaining the pulp_deb plugin (that is myself and ATIX). It is (no longer?) the only plugin with a separate CLI repo. (See: https://github.com/pulp/pulp-cli-ostree)

Also, the pulp-cli-deb repo's `main` branch now provides enough functionality to use it for sync workflows. Once I can figure out how to release the latest state, it is definitely worth packaging it.
